server:
  port: 8080
  shutdown: graceful

spring:
  main:
    web-application-type: NONE

  lifecycle:
    timeout-per-shutdown-phase: "60s"

  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:mysql://${DB_URL:localhost}:${DB_PORT:3306}/${DB_NAME:simtong}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: ${DDL:validate}
      properties:
        hibernate:
          format_sql: ${FORMAT_SQL:false}
          show_sql: ${SHOW_SQL:false}
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      open-in-view: false


  task:
    scheduling:
      pool:
        size: 8
      thread-name-prefix: simtong-scheduler-

feign:
  client:
    url:
      notification-server: ${NOTIFICATION_SERVER_URL}